#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Ruby development.
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 25 Feb 2015
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-node-dev-ubuntu"
export COMMON_DIR="provision-ubuntu-common"

git clone "git://github.com/neopragma/$COMMON_DIR"

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_sublime_text_3"
"./$COMMON_DIR/install_aptitude"
"./$COMMON_DIR/install_curl"

echo
echo '============================================================='
echo 'Installing NVM, node, and common packages

pushd "$HOME"
curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash
. ./nvm/nvm.sh
popd

npm install iojs
npm install grunt
npm install grunt-init
npm install bower
npm install yo
npm install jasmine-node
npm install grunt-jasmine-node-coverage

echo
echo '============================================================='
echo 'Setting the desktop background image...'

mkdir -p "$HOME/.backgrounds"
cp -f nodejs.png "$HOME/.backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/neopragma/.backgrounds/nodejs.png

echo
echo '============================================================='
echo 'Configuring sample project...'

pushd sample
cd sample
sudo npm install -g grunt-cli
npm install grunt --save-dev
popd

./verify
