#!/bin/bash
#======================================================================================
# Configure an instance of Ubuntu Linux to support Ruby development.
#
# Arguments:
# (None)		
#
# Version: 1.0.0
# Date: 25 Feb 2015
# Author: Dave Nicolette
#======================================================================================
export INSTALL_DIR="$HOME/provision-node-dev-ubuntu"
export COMMON_DIR="provision-ubuntu-common"

git clone "git://github.com/neopragma/$COMMON_DIR"

"./$COMMON_DIR/install_build_support"
"./$COMMON_DIR/install_sublime_text_3"
"./$COMMON_DIR/install_aptitude"
"./$COMMON_DIR/install_curl"

echo
echo '============================================================='
echo 'Installing NVM, node, and common packages

pushd "$HOME"
curl https://raw.githubusercontent.com/creationix/nvm/v0.23.3/install.sh | bash
. ./nvm/nvm.sh
popd

npm install iojs
npm install grunt
npm install grunt-init
npm install bower
npm install yo
npm install jasmine-node
npm install grunt-jasmine-node-coverage

# Set the Firefox bookmarks

pushd "$HOME/.mozilla/firefox"
PROFILEDIR=$(grep -n Path profiles.ini | cut -d '=' -f 2)
cd $PROFILEDIR
cp places.sqlite places-sqlite.orig
echo
echo '============================================================='
echo 'Setting Firefox bookmarks...'
echo "Copying places.sqlite from $RESOURCES to $(pwd)"
cp "$INSTALL_DIR/places.sqlite" .
popd

echo
echo '============================================================='
echo 'Setting the desktop background image...'

mkdir -p "$HOME/.backgrounds"
cp -f "$INSTALL_DIR/nodejs-background.png" "$HOME/.backgrounds/."
gsettings set org.gnome.desktop.background picture-uri file:///home/nodejsdev/.backgrounds/nodejs-background.png

echo
echo '============================================================='
echo 'Configuring sample project...'

pushd sample
cd sample
sudo npm install -g grunt-cli
npm install grunt --save-dev
popd

./verify
